general:
  description: !ENV example configuration with env ${PATH} # noqa
  name: example
git: null
input_data:
  pv:
    pv_files_groups:
      - label: solar_sheffield_passiv
        pv_filename: 5min_test.parquet
        pv_metadata_filename: metadata_passiv.csv
    get_center: false
    pv_image_size_meters_height: 10000000
    pv_image_size_meters_width: 10000000
    n_pv_systems_per_example: 1
    history_minutes: 60
    forecast_minutes: 120
output_data:
  filepath: not used by unittests!
process:
  batch_size: 4
  local_temp_path: ~/temp/
  seed: 1234
  upload_every_n_batches: 16
  n_train_batches: 2
  n_validation_batches: 0
  n_test_batches: 0
  train_test_validation_split: [3, 0, 1]
